language: cpp
dist: bionic
os: linux

jobs:
  include:
    # GCC 10 C++17
    - compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-10 && CXX=g++-10 && CXX_STANDARD=17"
      addons:
        apt:
          packages: libcrypto++-dev g++-10
          sources: &sources
            - ubuntu-toolchain-r-test
    # GCC 7 C++17
    - compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-7 && CXX=g++-7 && CXX_STANDARD=17"
      addons:
        apt:
          packages: libcrypto++-dev g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
    # GCC 5 C++14
    - compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-5 && CXX=g++-5 && CXX_STANDARD=14"
      addons:
        apt:
          packages: libcrypto++-dev g++-5
          sources: &sources
            - ubuntu-toolchain-r-test

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build
  - cd build
  - cmake -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=${COMPILER} -DCXX_STANDARD=${CXX_STANDARD} ..
  - make
